language: node_js
node_js:
  - "0.10"
  - "0.11"
  - "0.12"
env:
  global:
    # GOOGLE_USER
    - secure: "zAzJrsE92NwDoVb5M5rWp6lMdQJlLUAX/GJFx1ux9l5eTRb4F8Tv525tPfsG/+pbxoHF3yVNNGxejSsqSZZxWeywNhXWdsZycmf7iE1PnrdaPc2AoEohfG9j9v67VIFFWFtwh0XOk+UoTXXGfT197mD2BEmtkgIJkGQkhSIVgnI="
    # GOOGLE_PASSWORD
    - secure: "wWh+SAv4ZHe+7rqeJOXcACRRAsMZdhh+AwVAC22/AHR08iJBqUZnJ7r6dVb+NbpCT49Iu+RAAvGl3SDG7aSBNLYbUIBvdx4TRDfUEvh1nGprjRyKVPJgwm0KJIfwySq+lTlXM+QPgA1iRciT2cR3Fau5NEr6STFdbRTOrjfLK/w="
